set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR riscv32)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
list(APPEND CMAKE_TRY_COMPILE_PLATFORM_VARIABLES
    TOOLCHAIN_PREFIX
    TOOLCHAIN_TRIPLE)

set(TOOLCHAIN_TRIPLE "riscv-none-elf" CACHE STRING "RISC-V toolchain triple")
set(TOOLCHAIN_PREFIX "" CACHE PATH "RISC-V GCC install prefix; leave empty to find tools on PATH")

if(TOOLCHAIN_PREFIX)
    set(TOOLCHAIN_BIN_DIR "${TOOLCHAIN_PREFIX}/bin")
    set(_TOOLCHAIN_C_COMPILER "${TOOLCHAIN_BIN_DIR}/${TOOLCHAIN_TRIPLE}-gcc")
    set(_TOOLCHAIN_CXX_COMPILER "${TOOLCHAIN_BIN_DIR}/${TOOLCHAIN_TRIPLE}-g++")
else()
    if(CMAKE_C_COMPILER)
        set(_TOOLCHAIN_C_COMPILER "${CMAKE_C_COMPILER}")
    else()
        find_program(_TOOLCHAIN_C_COMPILER NAMES "${TOOLCHAIN_TRIPLE}-gcc")
    endif()
    if(CMAKE_CXX_COMPILER)
        set(_TOOLCHAIN_CXX_COMPILER "${CMAKE_CXX_COMPILER}")
    else()
        find_program(_TOOLCHAIN_CXX_COMPILER NAMES "${TOOLCHAIN_TRIPLE}-g++")
    endif()
    if(_TOOLCHAIN_C_COMPILER)
        get_filename_component(TOOLCHAIN_BIN_DIR "${_TOOLCHAIN_C_COMPILER}" DIRECTORY)
        get_filename_component(TOOLCHAIN_PREFIX "${TOOLCHAIN_BIN_DIR}/.." ABSOLUTE)
    endif()
endif()

if(NOT _TOOLCHAIN_C_COMPILER OR NOT EXISTS "${_TOOLCHAIN_C_COMPILER}")
    message(FATAL_ERROR
        "C compiler not found: ${_TOOLCHAIN_C_COMPILER}. Set TOOLCHAIN_PREFIX or add ${TOOLCHAIN_TRIPLE}-gcc to PATH.")
endif()
if(NOT _TOOLCHAIN_CXX_COMPILER OR NOT EXISTS "${_TOOLCHAIN_CXX_COMPILER}")
    message(FATAL_ERROR
        "C++ compiler not found: ${_TOOLCHAIN_CXX_COMPILER}. Set TOOLCHAIN_PREFIX or add ${TOOLCHAIN_TRIPLE}-g++ to PATH.")
endif()

set(CMAKE_C_COMPILER "${_TOOLCHAIN_C_COMPILER}" CACHE FILEPATH "C compiler")
set(CMAKE_CXX_COMPILER "${_TOOLCHAIN_CXX_COMPILER}" CACHE FILEPATH "C++ compiler")
set(CMAKE_ASM_COMPILER "${_TOOLCHAIN_C_COMPILER}" CACHE FILEPATH "ASM compiler")

set(CMAKE_AR
    "${TOOLCHAIN_BIN_DIR}/${TOOLCHAIN_TRIPLE}-ar"
    CACHE FILEPATH "Archiver")
set(CMAKE_RANLIB
    "${TOOLCHAIN_BIN_DIR}/${TOOLCHAIN_TRIPLE}-ranlib"
    CACHE FILEPATH "Ranlib")
set(CMAKE_OBJCOPY
    "${TOOLCHAIN_BIN_DIR}/${TOOLCHAIN_TRIPLE}-objcopy"
    CACHE FILEPATH "Objcopy")
set(CMAKE_OBJDUMP
    "${TOOLCHAIN_BIN_DIR}/${TOOLCHAIN_TRIPLE}-objdump"
    CACHE FILEPATH "Objdump")
set(CMAKE_SIZE
    "${TOOLCHAIN_BIN_DIR}/${TOOLCHAIN_TRIPLE}-size"
    CACHE FILEPATH "Size")

set(CMAKE_FIND_ROOT_PATH "${TOOLCHAIN_PREFIX}/${TOOLCHAIN_TRIPLE}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
